# -*- coding: utf-8 -*-
"""database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXOMLiD1Hma_jxV6anmbr9cvB9TvXu

## Import Packages
"""

import json
import os
import time
import base64
from io import BytesIO
from typing import List

import av
import gradio as gr
import numpy as np
import torch
from google.colab import userdata
from PIL import Image
from pymilvus import MilvusClient, AnnSearchRequest, RRFRanker, DataType
from transformers import AutoModel, AutoTokenizer

from langchain_community.vectorstores import Milvus
from langchain_core.embeddings import Embeddings
from langchain_core.messages import HumanMessage
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableLambda, RunnablePassthrough
from langchain_openai import ChatOpenAI
from langchain.prompts import PromptTemplate

"""---
## Utility Functions
"""
# Helper functions for video processing and data loading.

def load_metadata(json_filepath: str) -> dict:
    """Extracts specific metadata from a video's JSON metadata file."""
    with open(json_filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    video_id = data.get('original_json_filename', 'N/A').replace('.json', '')
    description = data.get('content_metadata', {}).get('description', 'N/A')
    return {
        'id': video_id,
        'description': description
    }

def load_embedding(video_output_dir: str) -> dict:
    """Loads embedding vectors from a specified directory."""
    metadata_path = os.path.join(video_output_dir, "metadata.json")
    with open(metadata_path, "r", encoding="utf-8") as f:
        metadata = json.load(f)
    video_emb = np.load(os.path.join(video_output_dir, metadata["embeddings"]["video_embeddings_path"]))
    text_emb = np.load(os.path.join(video_output_dir, metadata["embeddings"]["text_embeddings_path"]))
    return {
        "video_embeddings": np.squeeze(video_emb).tolist(),
        "text_embeddings": np.squeeze(text_emb).tolist()
    }

def pil_to_base64(image: Image) -> str:
    """Converts a PIL Image object to a base64-encoded string."""
    buffered = BytesIO()
    image.save(buffered, format="PNG")
    return base64.b64encode(buffered.getvalue()).decode("utf-8")

def extract_frames_by_count(video_path: str, num_frames: int = 8) -> List[Image.Image]:
    """Extracts a specified number of frames from a video."""
    frames = []
    container = av.open(video_path)
    stream = container.streams.video[0]
    total_frames = stream.frames
    interval = max(1, total_frames // num_frames)
    for i, frame in enumerate(container.decode(stream)):
        if len(frames) == num_frames:
            break
        if i % interval == 0:
            frames.append(frame.to_image())
    container.close()
    return frames

def get_base64_images_from_name(video_filename: str, video_dir: str = 'videos') -> List[str]:
    """
    Extracts frames from a video file and returns them as a list of base64 strings.
    """
    video_path = os.path.join(video_dir, video_filename)
    extracted_images = extract_frames_by_count(video_path)
    return [pil_to_base64(img) for img in extracted_images]

"""---
## Core Classes
"""

class EmbeddingModel:
    """
    Handles the X-CLIP model for generating text and video embeddings.
    """
    def __init__(self, model_name: str = "microsoft/xclip-base-patch32"):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModel.from_pretrained(model_name)
        print("Embedding model loaded.")

    def embed_documents(self, texts: List[str]) -> List[List[float]]:
        """Embeds a list of documents."""
        text_inputs = self.tokenizer(texts, padding=True, return_tensors="pt")
        text_features = self.model.get_text_features(**text_inputs)
        return text_features.tolist()

    def embed_query(self, text: str) -> List[float]:
        """Embeds a single text query."""
        text_inputs = self.tokenizer(text, padding=True, return_tensors="pt")
        text_features = self.model.get_text_features(**text_inputs)
        return text_features.tolist()[0]

class DatabaseManager:
    """
    Manages all interactions with the Milvus vector database.
    """
    def __init__(self, cluster_endpoint: str, token: str, collection_name: str = "video_metadata_collection"):
        self.client = MilvusClient(uri=cluster_endpoint, token=token)
        self.collection_name = collection_name
        self._ensure_collection_and_index()

    def _ensure_collection_and_index(self):
        """Creates or re-creates the collection and its indexes."""
        if self.client.has_collection(collection_name=self.collection_name):
            print(f"Collection '{self.collection_name}' exists. Dropping and recreating...")
            self.client.drop_collection(collection_name=self.collection_name)
            print("Collection dropped.")

        print(f"Creating collection '{self.collection_name}'...")
        schema = MilvusClient.create_schema(auto_id=False, enable_dynamic_field=False)
        schema.add_field(field_name="video_id", datatype=DataType.VARCHAR, is_primary=True, max_length=256)
        schema.add_field(field_name="video_embedding", datatype=DataType.FLOAT_VECTOR, dim=512)
        schema.add_field(field_name="text_embedding", datatype=DataType.FLOAT_VECTOR, dim=512)
        schema.add_field(field_name="video_filename", datatype=DataType.VARCHAR, max_length=512)
        schema.add_field(field_name="description", datatype=DataType.VARCHAR, max_length=4096)
        self.client.create_collection(collection_name=self.collection_name, schema=schema)
        print(f"Collection '{self.collection_name}' created.")

        index_params = self.client.prepare_index_params()
        index_params.add_index(field_name="video_embedding", metric_type="COSINE", index_type="IVF_FLAT", params={"nlist": 1024})
        index_params.add_index(field_name="text_embedding", metric_type="COSINE", index_type="AUTOINDEX")
        self.client.create_index(collection_name=self.collection_name, index_params=index_params)
        print("Indexes created.")

    def insert_data(self, data_path: str):
        """Inserts data from a specified path into the collection."""
        print("Inserting data...")
        for i in range(10):
            name = f"sample_{i}"
            emb_data = load_embedding(os.path.join(data_path, name))
            meta_data = load_metadata(os.path.join("metadata", name + '.json'))
            if emb_data and meta_data:
                data_to_insert = [{
                    "video_id": meta_data['id'],
                    "video_embedding": emb_data["video_embeddings"],
                    "text_embedding": emb_data["text_embeddings"],
                    "description": meta_data["description"],
                    "video_filename": name + '.mp4'
                }]
                self.client.insert(collection_name=self.collection_name, data=data_to_insert)
        self.client.flush(collection_name=self.collection_name)
        print("Data insertion complete and flushed.")

class RAGSystem:
    """
    Manages the entire RAG pipeline from query to response.
    """
    def __init__(self, db_manager: DatabaseManager, embedder: EmbeddingModel, openai_api_key: str):
        self.db_manager = db_manager
        self.embedder = embedder
        self.collection_name = self.db_manager.collection_name
        self.llm = ChatOpenAI(model="gpt-4o", api_key=openai_api_key)

    def hybrid_search_video_details(self, query: str) -> List[HumanMessage]:
        """
        Performs a hybrid search and retrieves video details and frames.
        Returns a list of HumanMessages for the LLM.
        """
        self.db_manager.client.load_collection(collection_name=self.collection_name)
        query_dense_vector = self.embedder.embed_query(query)
        ranker = RRFRanker(k=60)
        
        # Requests for both video and text embeddings
        reqs = [
            AnnSearchRequest(
                data=[query_dense_vector],
                anns_field="video_embedding",
                param={"nprobe": 10},
                limit=3
            ),
            AnnSearchRequest(
                data=[query_dense_vector],
                anns_field="text_embedding",
                param={"nprobe": 10},
                limit=3
            )
        ]
        
        results = self.db_manager.client.hybrid_search(
            collection_name=self.collection_name,
            reqs=reqs,
            ranker=ranker,
            limit=2
        )
        
        retrieved_ids = [hit.entity.get('video_id') for hits in results for hit in hits]
        
        if not retrieved_ids:
            return [HumanMessage(content=[{"type": "text", "text": "No relevant videos found."}])]

        retrieved_entities = self.db_manager.client.get(
            collection_name=self.collection_name,
            ids=retrieved_ids,
            output_fields=["video_filename", "description"]
        )
        
        if not retrieved_entities:
            return [HumanMessage(content=[{"type": "text", "text": "Failed to retrieve video details."}])]

        content_list = [{"type": "text", "text": query}]
        
        for entity in retrieved_entities:
            description = entity.get('description', 'No description available.')
            video_filename = entity.get('video_filename')
            
            if description:
                content_list.append({"type": "text", "text": f"Video Description: {description}"})
            
            if video_filename:
                base64_images = get_base64_images_from_name(video_filename)
                for img_base64 in base64_images:
                    content_list.append({"type": "image_url", "image_url": {"url": f"data:image/png;base64,{img_base64}"}})
        
        return [HumanMessage(content=content_list)]


    def create_rag_chain(self):
        """Builds and returns the LangChain RAG pipeline."""
        return RunnableLambda(self.hybrid_search_video_details) | self.llm | StrOutputParser()

"""---
## Gradio UI
"""

def main():
    """Main function to set up the system and launch the UI."""
    CLUSTER_ENDPOINT = userdata.get('CLUSTER_ENDPOINT')
    TOKEN = userdata.get('TOKEN')
    OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')
    
    # 1. Initialize core components
    embedder = EmbeddingModel()
    db_manager = DatabaseManager(CLUSTER_ENDPOINT, TOKEN)
    
    # Check if a specific file path is used for data insertion
    data_path_for_insertion = "test-embedding"
    db_manager.insert_data(data_path=data_path_for_insertion)
    
    rag_system = RAGSystem(db_manager, embedder, OPENAI_API_KEY)
    rag_chain = rag_system.create_rag_chain()

    def format_output(query):
        """Gradio handler function to format the output."""
        if not query.strip():
            return "Please enter a query."
        
        response = rag_chain.invoke(query)
        return f"**Response:**\n{response}\n"

    # 2. Create and launch the Gradio interface
    rag_interface = gr.Interface(
        fn=format_output,
        inputs=gr.Textbox(lines=2, placeholder="Ask a question about the video...", label="Your Query"),
        outputs=gr.Markdown(label="RAG Assistant Response"),
        title="Video-Based RAG Demo",
        description="Ask questions about the content of a video, and I'll retrieve relevant information and generate a response."
    )

    rag_interface.launch(share=True, debug=True)

if __name__ == "__main__":
    main()