# -*- coding: utf-8 -*-
"""database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXOMLiD1Hma_jxV3eganmbr9cvB9TvXu

## install packages
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd drive
# %cd MyDrive
# %cd intern

# !sudo apt update
# !sudo apt install -y docker.io
# !sudo systemctl start docker
# !sudo systemctl enable docker

!pip install av
!pip install langchain-openai

# !docker --version
# !docker compose version
!pip install pymilvus
!pip install -qU langchain-milvus pymilvus

!pip install -qU langchain-community

!pip install torch

from google.colab import userdata

# Connect using a MilvusClient object
from pymilvus import connections, DataType
from pymilvus import AnnSearchRequest, RRFRanker
from pymilvus import MilvusClient,Collection
from transformers import AutoModel, AutoTokenizer, AutoConfig,AutoProcessor

import json
import os
import torch
import numpy as np
import av
import os
import base64
from io import BytesIO
from PIL import Image
from typing import List

from langchain_milvus.retrievers import MilvusCollectionHybridSearchRetriever
from langchain_core.runnables import RunnableLambda
from langchain_core.messages import HumanMessage
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
from langchain_community.vectorstores import Milvus
from langchain_core.embeddings import Embeddings

"""## database creation"""

VIDEO_DIR = "./try_video/sample_0.mp4"
META_DIR = "./metadata"

# Retrieve your secrets
CLUSTER_ENDPOINT = userdata.get('CLUSTER_ENDPOINT')
TOKEN = userdata.get('TOKEN')
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')

# Set your token

# Initialize a MilvusClient instance
# Replace uri and token with your own
client = MilvusClient(
    uri=CLUSTER_ENDPOINT, # Cluster endpoint obtained from the console
    token=TOKEN # API key or a colon-separated cluster username and password
)

# if extracted_info:
#     print("--- Extracted Video Metadata ---")
#     print(f"ID: {extracted_info['id']}")
#     print(f"Title: {extracted_info['title']}")
#     print(f"Description: {extracted_info['description']}")
#     print(f"Text to Speech (first 50 chars): {extracted_info['text_to_speech'][:50]}...")
#     print("Character List:")
#     for char in extracted_info['characterList']:
#         print(f"  - Name: {char.get('name', 'N/A')}, Description: {char.get('description', 'N/A')}")
# else:
#     print("Failed to extract metadata.")

# 1. Define the Schema
# Using a fixed ID for simplicity, but you can use auto_id=True for auto-generated IDs
# For characterList, we'll store it as a JSON string within a VARCHAR field for now.
# If your Milvus version supports DataType.JSON (newer versions), you can use that.
schema = MilvusClient.create_schema(
    auto_id=False, # Set to True if you want Milvus to generate IDs
    enable_dynamic_field=False # Setting to False for explicit schema fields
)

schema.add_field(field_name="video_id", datatype=DataType.VARCHAR, is_primary=True, max_length=256)
# Add a vector field. You'd typically generate this from your video/text data using an embedding model.
vector_dimension = 512 # Example dimension, replace with your actual embedding dimension
schema.add_field(field_name="video_embedding", datatype=DataType.FLOAT_VECTOR, dim=vector_dimension)
schema.add_field(field_name="text_embedding", datatype=DataType.FLOAT_VECTOR, dim=vector_dimension)
schema.add_field(field_name="video_filename", datatype=DataType.VARCHAR, max_length=512)
schema.add_field(field_name="description", datatype=DataType.VARCHAR, max_length=4096)

# 3. Create the Collection
collection_name = "video_metadata_collection"
print(f"Checking if collection '{collection_name}' exists...")
if client.has_collection(collection_name=collection_name):
    print(f"Collection '{collection_name}' already exists. Dropping and recreating...")
    client.drop_collection(collection_name=collection_name)
    print("Collection dropped.")

print(f"Creating collection '{collection_name}'...")
client.create_collection(
    collection_name=collection_name,
    schema=schema,
    # index_params=index_params, # Remove index_params from create_collection
    # shards_num=2 # Example: You can set the number of shards
)
print(f"Collection '{collection_name}' created successfully.")

client.drop_index(
    collection_name=collection_name,
    index_name="vector_index"
)
# 5. Describe index
res = client.list_indexes(
    collection_name=collection_name
)
print(res)

# 4. Set up index
# 4.1. Set up the index parameters
index_params = client.prepare_index_params()

# 4.2. Add an index on the vector field.
# index_params.add_index(
#     field_name="video_embedding",
#     metric_type="COSINE",
#     index_type="AUTOINDEX",
#     index_name="vector_index"
# )
index_params.add_index(
    field_name="video_embedding",
    metric_type="COSINE",
    index_type="IVF_FLAT",
    params={"nlist": 1024},
    index_name="vector_index"
)


# 4.3. Add a second index on the 'text_embedding' field.
index_params.add_index(
    field_name="text_embedding",
    metric_type="COSINE",
    index_type="AUTOINDEX",
    index_name="text_vector_index" # Note: Added a new index_name
)
# 4.4. Create an index file
client.create_index(
    collection_name=collection_name ,
    index_params=index_params
)
# 5. Describe index
res = client.list_indexes(
    collection_name=collection_name
)
print(res)

"""### insert data"""

# ### insert data

# def load_embedding(video_output_dir):
#     # 加载元数据
#     with open(os.path.join(video_output_dir, "metadata.json"), "r", encoding="utf-8") as f:
#         metadata = json.load(f)

#     # 加载嵌入向量
#     video_emb = np.load(os.path.join(video_output_dir, metadata["embeddings"]["video_embeddings_path"]))
#     text_emb = np.load(os.path.join(video_output_dir, metadata["embeddings"]["text_embeddings_path"]))

#     return {
#         "video_embeddings": video_emb,
#         "text_embeddings": text_emb
#     }

# def insert_data_points(client, collection_name, data_points):
#     """
#     Inserts multiple data points into a Milvus collection.

#     Args:
#         client (MilvusClient): The Milvus client object.
#         collection_name (str): The name of the collection.
#         data_points (list): A list of dictionaries, where each dictionary
#                             represents a data point to be inserted.
#     """
#     try:
#         # The Milvus client.insert() method can accept a list of dictionaries
#         res = client.insert(
#             collection_name=collection_name,
#             data=data_points
#         )
#         print(f"Successfully inserted {len(data_points)} records into the collection.")
#         print("Insert result:", res)
#     except Exception as e:
#         print(f"An error occurred during insertion: {e}")

# # Example of how to use the new function
# # This is a placeholder for your actual data list
# # For example, you can create a list of dictionaries for the records to be inserted.
# # Each dictionary should have the same fields as your schema.
# # Assuming 'extracted_info' and embeddings are loaded as they are in your notebook
# video_embeddings = load_embedding(EMB_DIR)["video_embeddings"]
# text_embeddings = load_embedding(EMB_DIR)["text_embeddings"]
# extracted_info = load_metadata(os.path.join(META_DIR, "metadata.json"))

# # Create a list of dictionaries to be inserted
# data_to_insert = [
#     {
#         "video_id": extracted_info['id'],
#         "video_embedding": video_embeddings.tolist()[0],
#         "text_embedding": text_embeddings.tolist()[0],
#         "video_filename": "sample_0.mp4",
#         "description": extracted_info['description']
#     },
#     # Add more dictionaries for each record you want to insert
#     # {
#     #     "video_id": "another_id",
#     #     "video_embedding": [0.1, 0.2, ...],
#     #     "text_embedding": [0.3, 0.4, ...],
#     #     "video_filename": "another_video.mp4",
#     #     "description": "A description of another video."
#     # },
# ]

# # Call the function to insert the data
# # insert_data_points(client, collection_name, data_to_insert)

def load_embedding(video_output_dir):
    # 加载元数据
    with open(os.path.join(video_output_dir, "metadata.json"), "r", encoding="utf-8") as f:
        metadata = json.load(f)

    # 加载嵌入向量
    video_emb = np.load(os.path.join(video_output_dir, metadata["embeddings"]["video_embeddings_path"]))
    text_emb = np.load(os.path.join(video_output_dir, metadata["embeddings"]["text_embeddings_path"]))

    return {
        "video_embeddings": video_emb,
        "text_embeddings": text_emb
    }

# 使用

def load_metadata(json_filepath):
    """
    Extracts specific metadata (id, title, description, text_to_speech, characterList)
    from a video's JSON metadata file.

    Args:
        json_filepath (str): The path to the JSON metadata file.

    Returns:
        dict: A dictionary containing the extracted metadata, or None if an error occurs.
    """
    try:
        with open(json_filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Extracting 'id' from 'original_json_filename' by removing the '.json' extension
        video_id = data.get('original_json_filename', 'N/A').replace('.json', '')

        # Extracting 'title' from 'content_metadata.title'
        title = data.get('content_metadata', {}).get('title', 'N/A')

        # Extracting 'description' from 'content_metadata.description'
        # Note: There's also youtube_description, you might choose one or combine them
        description = data.get('content_metadata', {}).get('description', 'N/A')

        # Extracting 'text_to_speech'
        text_to_speech = data.get('text_to_speech', 'N/A')

        # Extracting 'characterList'
        character_list = data.get('content_metadata', {}).get('characterList', [])

        extracted_data = {
            'id': video_id,
            'title': title,
            'description': description,
            'text_to_speech': text_to_speech,
            'characterList': character_list
        }
        return extracted_data

    except FileNotFoundError:
        print(f"Error: File not found at {json_filepath}")
        return None
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON format in {json_filepath}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return None

for i in range(10):
  name =  f"sample_{i}"
  result = load_embedding("test-embedding/" +name)
  video_embedding = np.squeeze(result["video_embeddings"]).tolist()
  text_embedding = np.squeeze(result["text_embeddings"]).tolist()
  # print("视频嵌入形状:", result["video_embeddings"].shape)

  metadata = load_metadata("metadata/"+name+'.json')
  video_fileename = name +'.mp4'
  description = metadata['description']
  id = metadata['id']
  print(video_fileename)
  print(metadata.keys())
  print(description)

  data_to_insert = [
    {
        "video_id": id,
        "video_embedding": video_embedding,# Use the converted list of floats
        "text_embedding": text_embedding,
        "description":description,
        "video_filename":video_fileename
    }]

  # 5. Insert Data
  print(f"Inserting data into '{collection_name}'...")
  insert_result = client.insert(
      collection_name=collection_name,
      data=data_to_insert
  )
  print("Data insertion initiated.")
  print(f"Insert count: {insert_result['insert_count']}")

  # Important: Flush data to ensure it's queryable immediately
  # In a production environment, you might let Milvus auto-flush or flush periodically.
  # Flushing too often can lead to fragmented segments.
print("Flushing data...")
client.flush(collection_name=collection_name)
print("Data flushed.")

# 4. Prepare Data for Insertion
# Milvus expects a list of dictionaries, where each dictionary is an entity.
# For the `video_embedding` field, you'll need to generate an actual vector.
# For this example, we'll use a dummy vector.
# Convert characterList to a JSON string for storage in VARCHAR
# character_list_json_str = json.dumps(extracted_info['characterList'])

# Convert the torch tensor to a list of floats
# video_embedding_list = embed.squeeze().tolist()


data_to_insert = [
    {
        "video_id": id,
        "video_embedding": video_embedding,# Use the converted list of floats
        "text_embedding": text_embedding,
        "description":description,
        "video_filename":video_fileename
    }
]

# 5. Insert Data
print(f"Inserting data into '{collection_name}'...")
insert_result = client.insert(
    collection_name=collection_name,
    data=data_to_insert
)
print("Data insertion initiated.")
print(f"Insert count: {insert_result['insert_count']}")

# Important: Flush data to ensure it's queryable immediately
# In a production environment, you might let Milvus auto-flush or flush periodically.
# Flushing too often can lead to fragmented segments.
print("Flushing data...")
client.flush(collection_name=collection_name)
print("Data flushed.")

"""## id retrival"""

client.load_collection(collection_name=collection_name)

# # Retrieve video names by ID
# # inserted_ids = results[0][0]['video_id']
# inserted_ids = extracted_info['id']
# print(f"Retrieved IDs: {inserted_ids}")
# #
# try:
#     # Load the collection into memory for searching/querying
#     client.load_collection(collection_name=collection_name)

#     retrieved_entities = client.get(
#         collection_name=collection_name,
#         ids=inserted_ids,
#         output_fields=["video_filename","description"]
#         # output_fields=["video_id",  "video_embedding", "text_embedding","video_filename"] # Specify all fields you want to see
#     )
#     print(f'Retrieved Entities: {retrieved_entities}')
#     print("Retrieved Entities:")
#     for entity in retrieved_entities:
#         print(entity)

# finally:
#     # Always release the collection when done to free up memory
#     print(f"Releasing collection '{collection_name}' from memory.")
#     client.release_collection(collection_name=collection_name)

"""## text retrival

### use original model
"""

model = AutoModel.from_pretrained("microsoft/xclip-base-patch32")
video_embd_func = model.get_video_features
tokenizer = AutoTokenizer.from_pretrained("microsoft/xclip-base-patch32")

"""### use fintuned model"""

# # Define the path to your model directory
# local_model_path = "./model"

# # List all the .bin files in the directory
# # This assumes your sharded files are named like 'pytorch_model.bin.0000x-of-0000y'
# bin_files = sorted([f for f in os.listdir(local_model_path) if f.endswith('.bin')])

# if not bin_files:
#     raise FileNotFoundError("No .bin files found in the specified directory.")

# # Manually load and combine the state dictionaries from each shard
# state_dict = {}
# for file_name in bin_files:
#     file_path = os.path.join(local_model_path, file_name)
#     print(f"Loading shard: {file_path}")
#     try:
#         # Crucially, set weights_only=False to bypass the PyTorch 2.6 error
#         shard = torch.load(file_path, map_location="cpu", weights_only=False)
#         state_dict.update(shard)
#     except Exception as e:
#         print(f"Error loading {file_path}: {e}")
#         break

# # Get the configuration for the base model
# base_model_name = "microsoft/xclip-base-patch32" # Replace with your base model
# config = AutoConfig.from_pretrained(base_model_name)

# # Create an empty model from the configuration
# model = AutoModel.from_config(config)

# # Load the combined state dictionary into the model
# model.load_state_dict(state_dict, strict=False)

# print("Model loaded successfully!")

video_embd_func = model.get_video_features
tokenizer = AutoTokenizer.from_pretrained("microsoft/xclip-base-patch32")

client.load_collection(collection_name=collection_name)
# The search parameters, which should match the index you've created on the collection
search_params = {
    "metric_type": "COSINE", # or "L2" or "IP"
    "params": {"nprobe": 10}, # Adjust nprobe based on your index type and needs
}
# Example query vector (replace with your actual embedding)
query_vector = np.random.rand(512).astype(np.float32).tolist()
# Perform the search on the video_embedding field
results = client.search(
    collection_name=collection_name,
    data=[query_vector],
    anns_field="video_embedding",
    limit=10,
    search_params=search_params,
    output_fields=["video_id", "video_filename"]
)

# Load the tokenizer and model outside the class, so they are initialized only once
# tokenizer = AutoTokenizer.from_pretrained("microsoft/xclip-base-patch32")
# model = AutoModel.from_pretrained("microsoft/xclip-base-patch32")

class XClipEmbeddings(Embeddings):
    """
    Custom Embeddings class to wrap the Hugging Face X-CLIP model for LangChain.
    """
    def __init__(self, tokenizer, model):
        self.tokenizer = tokenizer
        self.model = model

    def embed_documents(self, texts: List[str]) -> List[List[float]]:
        """
        Embeds a list of documents.
        """
        # Tokenize the text inputs
        text_inputs = self.tokenizer(texts, padding=True, return_tensors="pt")
        # Get the text features from the model
        text_features = self.model.get_text_features(**text_inputs)
        # Return as a list of lists
        return text_features.tolist()

    def embed_query(self, text: str) -> List[float]:
        """
        Embeds a single text query.
        """
        # Tokenize the single text input
        text_inputs = self.tokenizer(text, padding=True, return_tensors="pt")
        # Get the text features from the model
        text_features = self.model.get_text_features(**text_inputs)
        # Return the first (and only) embedding as a single list
        return text_features.tolist()[0]

# Initialize the custom class with the pre-loaded tokenizer and model
xclip_embeddings = XClipEmbeddings(tokenizer, model)

"""## text RAG"""

# Example: Embed a list of documents
documents = ["a photo of a cat", "a man walking in the park"]
doc_embeddings = xclip_embeddings.embed_documents(documents)

# Example: Embed a single query
query = "a picture of a dog"
query_embedding = xclip_embeddings.embed_query(query)

print("Document embeddings shape:", len(doc_embeddings), len(doc_embeddings[0]))
print("Query embedding shape:", len(query_embedding))

ZILLIZ_CLOUD_URI = 'https://in03-b510f824c907c11.serverless.aws-eu-central-1.cloud.zilliz.com'
ZILLIZ_CLOUD_USERNAME = 'db_b510f824c907c11'
ZILLIZ_CLOUD_PASSWORD = 'Vk8>1JOsDpAcD-q|'

# Connect to the existing collection
vector_db = Milvus(
    embedding_function =xclip_embeddings,
    connection_args={
        "uri": ZILLIZ_CLOUD_URI,
        "user": ZILLIZ_CLOUD_USERNAME,
        "password": ZILLIZ_CLOUD_PASSWORD,
        "secure": True,
    },
    collection_name=collection_name,
    vector_field="video_embedding",
    text_field="description"
)

# Convert the Milvus vector store into a retriever
# This makes it a standard LangChain component that can be used in a chain
retriever = vector_db.as_retriever(search_kwargs={"k": 4})

# Define a prompt template for your RAG system
template = """
You are an AI assistant. Use the following pieces of retrieved context to answer the question.
If you don't know the answer, just say that you don't know.
Context: {context}
Question: {question}
"""
prompt = PromptTemplate.from_template(template)

# Define your LLM
llm = ChatOpenAI(model="gpt-5-nano",api_key=OPENAI_API_KEY)

# Build the RAG chain
# The retriever will fetch the most relevant context, and the LLM will generate a response
rag_chain = (
    {"context":retriever  , "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

# Assuming 'retriever' has been defined as in the original code
query = "What is Retrieval-Augmented Generation?"
retrieved_docs = retriever.invoke(query)

# Print the number of documents retrieved
print(f"Retrieved {len(retrieved_docs)} documents.")

# Iterate and print the content and metadata of each document
for i, doc in enumerate(retrieved_docs):
    print(f"\n--- Document {i+1} ---")
    print(f"Content: {doc.page_content[:200]}...")  # Print the first 200 characters
    print(f"Metadata: {doc.metadata}")

user_query = "What do these images show?"
# Invoke the chain with a user query
response = rag_chain.invoke(user_query)

print(response)

"""## video-text RAG"""

def pil_to_base64(image: Image) -> str:
    buffered = BytesIO()
    image.save(buffered, format="PNG")
    return base64.b64encode(buffered.getvalue()).decode("utf-8")

def extract_frames_by_count(video_path, num_frames=8):
    container = av.open(video_path)
    stream = container.streams.video[0]
    total_frames = stream.frames

    if total_frames < num_frames:
        print("Video has fewer than 8 frames.")
        return []

    interval = max(1, total_frames // num_frames)
    frames = []

    for i, frame in enumerate(container.decode(stream)):
        if len(frames) == num_frames:
            break
        if i % interval == 0:
            frames.append(frame.to_image())

    container.close()
    return frames
# path = 'videos'
# video = results[0][0]['video_filename']
# video_path = os.path.join(path,video)
# # Usage example:
# extracted_images = extract_frames_by_count(video_path)

def get_base64_images_from_name(video_filename,  video_dir='videos'):
    # Step 2: Construct the full video path
    video_path = os.path.join(video_dir, video_filename)

    # Step 3: Extract frames from the video
    extracted_images = extract_frames_by_count(video_path)

    # Step 4: Convert frames to base64 strings
    base64_images = [pil_to_base64(img) for img in extracted_images]

    return base64_images

# Assuming 'client' and 'xclip_embeddings' are already initialized and accessible
# in your environment.

def hybrid_search_video_details(query):
    # Initialize the ranker
    ranker = RRFRanker(100)

    # Get the dense vector embedding for the query
    query_dense_vector = xclip_embeddings.embed_query(query)

    # Define search parameters and requests for both text and video embeddings
    text_search_params = {
        "data": [query_dense_vector],
        "anns_field": "text_embedding",
        "param": {"nprobe": 10},
        "limit": 2
    }
    request_text = AnnSearchRequest(**text_search_params)
    print(f'request_text {request_text}')
    video_search_params = {
        "data": [query_dense_vector],
        "anns_field": "video_embedding",
        "param": {"nprobe": 10},
        # to make right video to be retrived
        "limit": 5
    }

    request_video = AnnSearchRequest(**video_search_params)
    print(f'request_video {request_video}')
    # reqs = [request_video]
    reqs = [request_text, request_video]


    # Perform the hybrid search parallelly
    res = client.hybrid_search(
        collection_name="video_metadata_collection",
        reqs=reqs,
        ranker=ranker,
        limit=2
    )

    video_details = []
    # Extract the required details from the results
    for hits in res:
        for hit in hits:
            retrieved_entities = client.get(
                        collection_name=collection_name,
                        ids=hit.entity.get('video_id'),
                        output_fields=["video_filename","description"])

            print(retrieved_entities[0])
            details = {
                'video_id': hit.entity.get('video_id'),
                'description': retrieved_entities[0]['description'],
                'video_filename': retrieved_entities[0]['video_filename']
            }
            video_details.append(details)
    content_list = []
    file_name = video_details[0]['video_filename']
    base64_images = get_base64_images_from_name(file_name)
    # Must be a PromptValue, str, or list of BaseMessages to chained successfully
    # HumanMessage expects a list of dict for multimodal
    query_message = {"type": "text", "text": query}
    description_message = {"type":"text", "text": video_details[0]['description']}
    content_list.append(query_message)
    content_list.append(description_message)
    for img_base64 in base64_images:
      image_message = {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{img_base64}"}}
      content_list.append(image_message)

    message = HumanMessage(content=content_list)
    return [message]

query = 'video about police recruits'

client.load_collection(collection_name=collection_name)
# hybrid_search_video_id('video about academic')
m = hybrid_search_video_details(query)

run_retriver = RunnableLambda(hybrid_search_video_details)

run_retriver.invoke(query)

video_rag_chain = RunnableLambda(hybrid_search_video_details) | llm | StrOutputParser()

# response = video_rag_chain.invoke(query)

print(type(response))

print(response)

"""## demo UI"""

import gradio as gr
import time
import json

# This is a placeholder for your actual RAG backend function.
# In a real-world scenario, this function would:
# 1. Take the user's query.
# 2. Call your backend RAG API or model.
# 3. Return a dictionary containing the generated response and source information.
# The structure should match the example data below.
def query_rag_model(query):
    """
    Simulates a call to a RAG model backend.

    Args:
        query (str): The user's input query.

    Returns:
        dict: A dictionary containing the response and source references.
              - "response": The main generated text.
              - "sources": A list of dictionaries with "url" and "title" for sources.
    """
    print(f"Received query: '{query}'")
    content = video_rag_chain.invoke(query)
    example_response = {'response': content}
    # Example response data structure. Your backend should return something similar.
    # Note: A real implementation would dynamically generate this based on the query.
    # example_response = {
    #     "response": f"Based on your query about '{query}', the academy focuses on physical fitness, tactical training, and legal studies to prepare recruits for the Queensland Police Service. This is an example of a generated response from the RAG model.",
    #     "sources": [
    #         {
    #             "url": "https://www.police.qld.gov.au/recruit",
    #             "title": "Queensland Police Recruit Training"
    #         },
    #         {
    #             "url": "https://www.youtube.com/watch?v=samplevideo",
    #             "title": "A Day in the Life of a QPS Recruit"
    #         }
    #     ]
    # }

    return example_response

def format_output(query):
    """
    This function acts as the Gradio interface handler.
    It calls the RAG model function and formats the output for display.
    """
    # Check if the query is empty
    if not query.strip():
        return "Please enter a query."

    # Call the RAG model function
    response_data = query_rag_model(query)

    # Format the response with markdown
    formatted_text = f"**Response:**\n{response_data['response']}\n\n"

    # Add source references if available
    if response_data.get("sources"):
        formatted_text += "**Sources:**\n"
        for source in response_data["sources"]:
            formatted_text += f"- [{source['title']}]({source['url']})\n"

    return formatted_text

# Create the Gradio interface
# The interface takes the main function, the input components, and the output components.
rag_interface = gr.Interface(
    fn=format_output,
    inputs=gr.Textbox(lines=2, placeholder="Ask a question about the video...", label="Your Query"),
    outputs=gr.Markdown(label="RAG Assistant Response"),
    title="Video-Based RAG Demo",
    description="Ask questions about the content of a video, and I'll retrieve relevant information and generate a response."
)

# Launch the Gradio app
if __name__ == "__main__":
    # The share=True option creates a public URL you can share for a limited time.
    rag_interface.launch(share=True, debug=True)