# -*- coding: utf-8 -*-
"""embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9uUijH88IVQcC6sfnBPXdkXF5Su6hoQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd drive
# %cd MyDrive
# %cd intern

!pip install av transformers huggingface_hub torch numpy

import av
import torch
import numpy as np
import json

from transformers import AutoProcessor, AutoModel,AutoTokenizer
from huggingface_hub import hf_hub_download

np.random.seed(0)

def read_video_pyav(container, indices):
    '''
    Decode the video with PyAV decoder.
    Args:
        container (`av.container.input.InputContainer`): PyAV container.
        indices (`list[int]`): List of frame indices to decode.
    Returns:
        result (np.ndarray): np array of decoded frames of shape (num_frames, height, width, 3).
    '''
    frames = []
    container.seek(0)
    start_index = indices[0]
    end_index = indices[-1]
    for i, frame in enumerate(container.decode(video=0)):
        if i > end_index:
            break
        if i >= start_index and i in indices:
            frames.append(frame)
    return np.stack([x.to_ndarray(format="rgb24") for x in frames])

def sample_frame_indices(clip_len, frame_sample_rate, seg_len):
    '''
    Sample a given number of frame indices from the video.
    Args:
        clip_len (`int`): Total number of frames to sample.
        frame_sample_rate (`int`): Sample every n-th frame.
        seg_len (`int`): Maximum allowed index of sample's last frame.
    Returns:
        indices (`list[int]`): List of sampled frame indices
    '''
    converted_len = int(clip_len * frame_sample_rate)
    end_idx = np.random.randint(converted_len, seg_len)
    start_idx = end_idx - converted_len
    indices = np.linspace(start_idx, end_idx, num=clip_len)
    indices = np.clip(indices, start_idx, end_idx - 1).astype(np.int64)
    return indices

# video clip consists of 300 frames (10 seconds at 30 FPS)
# file_path = hf_hub_download(
#     repo_id="nielsr/video-demo", filename="eating_spaghetti.mp4", repo_type="dataset"
# )
file_path = './try_video/sample_0.mp4'
container = av.open(file_path)

# sample 8 frames
indices = sample_frame_indices(clip_len=8, frame_sample_rate=1, seg_len=container.streams.video[0].frames)
video = read_video_pyav(container, indices)

processor = AutoProcessor.from_pretrained("microsoft/xclip-base-patch32")
model = AutoModel.from_pretrained("microsoft/xclip-base-patch32")

inputs = processor(
    # text=["playing sports", "eating spaghetti", "go shopping"],
    videos=list(video),
    return_tensors="pt",
    # padding=True,
)

video_features = model.get_video_features(**inputs)
print(video_features.shape)
torch.save(video_features, "./embeddings/sample_0.pt")

def extract_video_metadata(json_filepath):
    """
    Extracts specific metadata (id, title, description, text_to_speech, characterList)
    from a video's JSON metadata file.

    Args:
        json_filepath (str): The path to the JSON metadata file.

    Returns:
        dict: A dictionary containing the extracted metadata, or None if an error occurs.
    """
    try:
        with open(json_filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Extracting 'id' from 'original_json_filename' by removing the '.json' extension
        video_id = data.get('original_json_filename', 'N/A').replace('.json', '')

        # Extracting 'title' from 'content_metadata.title'
        title = data.get('content_metadata', {}).get('title', 'N/A')

        # Extracting 'description' from 'content_metadata.description'
        # Note: There's also youtube_description, you might choose one or combine them
        description = data.get('content_metadata', {}).get('description', 'N/A')

        # Extracting 'text_to_speech'
        text_to_speech = data.get('text_to_speech', 'N/A')

        # Extracting 'characterList'
        character_list = data.get('content_metadata', {}).get('characterList', [])

        extracted_data = {
            'id': video_id,
            'title': title,
            'description': description,
            'text_to_speech': text_to_speech,
            'characterList': character_list
        }
        return extracted_data

    except FileNotFoundError:
        print(f"Error: File not found at {json_filepath}")
        return None
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON format in {json_filepath}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return None

json_filename = "metadata/sample_0.json"

# Path to your JSON file
# For your provided data, it would be 'sample_0.json' if saved locally.
# We'll use the dummy file for this example.
json_file = "metadata/sample_0.json"
extracted_info = extract_video_metadata(json_file)
if extracted_info:
    print("--- Extracted Video Metadata ---")
    print(f"ID: {extracted_info['id']}")
    print(f"Title: {extracted_info['title']}")
    print(f"Description: {extracted_info['description']}")
    print(f"Text to Speech (first 50 chars): {extracted_info['text_to_speech'][:50]}...")
    print("Character List:")
    for char in extracted_info['characterList']:
        print(f"  - Name: {char.get('name', 'N/A')}, Description: {char.get('description', 'N/A')}")
else:
    print("Failed to extract metadata.")

tokenizer = AutoTokenizer.from_pretrained("microsoft/xclip-base-patch32")
text_inputs = tokenizer(extracted_info['description'], padding=True, return_tensors="pt")
text_features = model.get_text_features(**text_inputs)

text_features.shape

video_features.shape